#!/usr/bin/python3

import os
import sys
import time


def test_check_unlocked():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f check_approtect.ocd")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46")
    print("Info : Hardware version: 8.00")
    print("Info : VTarget = 3.274 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Error: nrf52.cpu -- clearing lockup after double fault")
    print("Polling target nrf52.cpu failed, trying to reexamine")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Info : gdb port disabled")
    print("nRF52 device has no active AP Protection. :)")
    print("Info : nRF52832-QFAA(build code: B0) 512kB Flash, 64kB RAM")
    print("")
    print("")
    print("shutdown command invoked")
    print("")

def test_check_locked():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f check_approtect.ocd")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46")
    print("Info : Hardware version: 8.00")
    print("Info : VTarget = 3.274 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Error: Could not find MEM-AP to control the core")
    print("****** WARNING ******")
    print("nRF52 device has AP lock engaged (see UICR APPROTECT register).")
    print("Debug access is denied.")
    print("Use 'nrf52_recover' to erase and unlock the device.")
    print("")
    print("Info : gdb port disabled")
    print("nRF52 device has active AP Protection. :/")
    print("")
    print("shutdown command invoked")
    print("")

def test_check_notfound():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f check_approtect.ocd")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46")
    print("Info : Hardware version: 8.00")
    print("Info : VTarget = 3.274 V")
    print("Info : clock speed 1000 kHz")
    print("")
    print("")

def test_lock():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f set_approtect.ocd")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46")
    print("Info : Hardware version: 8.00")
    print("Info : VTarget = 3.274 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Info : gdb port disabled")
    print("Info : nRF52832-QFAA(build code: B0) 512kB Flash, 64kB RAM")
    print("shutdown command invoked")
    print("")

def test_unlock():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f set_approtect.ocd")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46")
    print("Info : Hardware version: 8.00")
    print("Info : VTarget = 3.274 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Info : gdb port disabled")
    print("Info : nRF52832-QFAA(build code: B0) 512kB Flash, 64kB RAM")
    print("shutdown command invoked")
    print("")

def test_program():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f board.ocd -c \"program /home/max/Downloads/prod/coin_d3f33cc55c04.hex verify exit\"")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link V9 compiled Dec 13 2019 11:14:50")
    print("Info : Hardware version: 9.60")
    print("Info : VTarget = 3.314 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Error: nrf52.cpu -- clearing lockup after double fault")
    print("Polling target nrf52.cpu failed, trying to reexamine")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Info : gdb port disabled")
    print("target halted due to debug-request, current mode: Thread ")
    print("xPSR: 0x01000000 pc: 0xfffffffe msp: 0xfffffffc")
    print("** Programming Started **")
    print("Info : nRF52840-xxAA(build code: D0) 1024kB Flash, 256kB RAM")
    print("Warn : Flash protection of this nRF device is not supported")
    print("Info : Flash write discontinued at 0x0001c93e, next section at 0x00032000")
    print("Info : Padding image section 0 at 0x0001c93e with 2 bytes (bank write end alignment)")
    print("Warn : Adding extra erase range, 0x0001c940 .. 0x0001cfff")
    print("Warn : Adding extra erase range, 0x10001000 .. 0x10001207")
    print("Warn : Adding extra erase range, 0x1000120c .. 0x10001fff")
    time.sleep(1)
    print("** Programming Finished **")
    print("** Verify Started **")
    time.sleep(1)
    print("** Verified OK **")
    print("shutdown command invoked")
    print("")

def test_program_fail():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f board.ocd -c \"program /home/max/Downloads/prod/coin_d3f33cc55c04.hex verify exit\"")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link V9 compiled Dec 13 2019 11:14:50")
    print("Info : Hardware version: 9.60")
    print("Info : VTarget = 3.314 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Error: nrf52.cpu -- clearing lockup after double fault")
    print("Polling target nrf52.cpu failed, trying to reexamine")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Info : gdb port disabled")
    print("target halted due to debug-request, current mode: Thread ")
    print("xPSR: 0x01000000 pc: 0xfffffffe msp: 0xfffffffc")
    print("** Programming Started **")
    print("Info : nRF52840-xxAA(build code: D0) 1024kB Flash, 256kB RAM")
    print("Warn : Flash protection of this nRF device is not supported")
    print("Info : Flash write discontinued at 0x0001c93e, next section at 0x00032000")
    print("Info : Padding image section 0 at 0x0001c93e with 2 bytes (bank write end alignment)")
    print("Warn : Adding extra erase range, 0x0001c940 .. 0x0001cfff")
    time.sleep(1)
    print("** Programming Failed **")
    print("shutdown command invoked")
    print("")

def test_program_verification_fail():
    print("max@grautvornix:~/keykeeper-manager$ ~/Downloads/xpack-openocd-0.10.0-14/bin/openocd -c \"gdb_port disabled\" -c \"tcl_port disabled\" -c \"telnet_port disabled\" -f interface/jlink.cfg -f board.ocd -c \"program /home/max/Downloads/prod/coin_d3f33cc55c04.hex verify exit\"")
    print("xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00378-ge5be992df (2020-06-26-09:27)")
    print("Licensed under GNU GPL v2")
    print("For bug reports, read")
    print("	http://openocd.org/doc/doxygen/bugs.html")
    print("Info : J-Link V9 compiled Dec 13 2019 11:14:50")
    print("Info : Hardware version: 9.60")
    print("Info : VTarget = 3.314 V")
    print("Info : clock speed 1000 kHz")
    print("Info : SWD DPIDR 0x2ba01477")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Error: nrf52.cpu -- clearing lockup after double fault")
    print("Polling target nrf52.cpu failed, trying to reexamine")
    print("Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints")
    print("Info : gdb port disabled")
    print("target halted due to debug-request, current mode: Thread ")
    print("xPSR: 0x01000000 pc: 0xfffffffe msp: 0xfffffffc")
    print("** Programming Started **")
    print("Info : nRF52840-xxAA(build code: D0) 1024kB Flash, 256kB RAM")
    print("Warn : Flash protection of this nRF device is not supported")
    print("Info : Flash write discontinued at 0x0001c93e, next section at 0x00032000")
    print("Info : Padding image section 0 at 0x0001c93e with 2 bytes (bank write end alignment)")
    print("Warn : Adding extra erase range, 0x0001c940 .. 0x0001cfff")
    print("Warn : Adding extra erase range, 0x10001000 .. 0x10001207")
    print("Warn : Adding extra erase range, 0x1000120c .. 0x10001fff")
    time.sleep(1)
    print("** Programming Finished **")
    print("** Verify Started **")
    time.sleep(1)
    print("** Verify Failed **")
    print("shutdown command invoked")
    print("")

if __name__ == "__main__":
    if len(sys.argv) == 2:
        if sys.argv[1] == 'check_unlocked':
            test_check_unlocked()
        elif sys.argv[1] == 'check_locked':
            test_check_locked()
        elif sys.argv[1] == 'check_notfound':
            test_check_notfound()
        elif sys.argv[1] == 'lock':
            test_lock()
        elif sys.argv[1] == 'unlock':
            test_unlock()
        elif sys.argv[1] == 'program':
            test_program()
        elif sys.argv[1] == 'program_fail':
            test_program_fail()
        elif sys.argv[1] == 'program_verification_fail':
            test_program_verification_fail()